pipeline {
    agent {
        dockerfile {
            dir 'unified-agent-automation'
            args '-v /root/.m2:/root/.m2 -v /var/lib/jenkins/.m2/settings.xml:/usr/share/maven/conf/settings.xml'
        }
     }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

    }
}
